### PR TITLE
1.0.18 from defaults

### PR DESCRIPTION
**Pull request by teake**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This merges most changes from the [defaults recipe](https://github.com/AnacondaRecipes/libsodium-feedstock). Driver for this PR is https://github.com/conda-forge/pynacl-feedstock/pull/16#issuecomment-658162268.

If the build passes this will supersede #17.

**Note** I haven't tested anything, this is a glorified copy-paste job from defaults!

### CODE REVIEW

**Comment by teake** [comment]
Note: the Windows build [has the following warning](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=184203&view=logs&j=f97ca392-d626-52d0-4b2e-4b27aa319a77&t=7b750183-140d-50ae-3ee1-cbef6218bdf6&l=1070) about a missing library:
```
WARNING (libsodium,Library\bin\libsodium.dll): Needed DSO C:\Windows\System32\VCRUNTIME140.dll not found in any CDT/compiler package, nor the whitelist?!
```
Not sure how that relates to a commit in this PR (74770e0a67a7ad3b03cffa8fd5d746eb6a77ece9), which I did just to mimic the defaults recipe.

**Comment by CJ-Wright** [comment]
@conda-forge/libsodium

**Comment by CJ-Wright** [comment]
@teake are you interested in becoming a maintainer?

**Comment by jakirkham** [comment]
I don't know that much about the Windows code here unfortunately. @nehaljwani @mingwandroid @SylvainCorlay , would you be able to comment here?

Would add though we dropped VS2008 in conda-forge as a whole a while ago. It would be good to drop that from the recipe too.

**Comment by teake** [comment]
> @teake are you interested in becoming a maintainer?

No, not really. I had hoped this would be one-off.

**Comment by nehaljwani** [comment]
The vs2008 build was added for supporting py27 builds of pynacl, IIRC. Now that py27 is EOL, we should get rid of it.

**Comment by CJ-Wright** [comment]
@conda-forge/libsodium ping!

**Comment by tschoonj** [comment]
Could someone merge this PR in please?

Thanks!

**Pull request merged**
