### PR TITLE
Bump to version 1.0.17

### PR DESCRIPTION
**Pull request by bartvm**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes https://github.com/conda-forge/libsodium-feedstock/pull/13

### CODE REVIEW

**Comment by bartvm** [comment]
@conda-forge-admin, please rerender

**Comment by bartvm** [comment]
Windows builds pass on Appveyor but fail on Azure, not sure what that means.

**Comment by jakirkham** [comment]
Failures of Windows builds on Azure is a known issue and can be ignored.

**Comment by jakirkham** [comment]
Thanks @bartvm! Also welcome to conda-forge. 😄

**Pull request merged**
