### PR TITLE
conda-build 3, run_exports

### PR DESCRIPTION
**Pull request by minrk**
after investigating https://github.com/conda-forge/zeromq-feedstock/issues/36 I discovered that libsodium can bump its ABI version in patch releases, so we need to pin it down.

### CODE REVIEW

**Comment by stuarteberg** [comment]
Travis is failing. Looks like this line needs to change, if I understand correctly:

```diff
-    - {{ pin_subpackage(name, max_pin="x.x.x") }}
+    - {{ pin_subpackage('libsodium', max_pin="x.x.x") }}

```

**Comment by CJ-Wright** [comment]
@conda-forge-admin please re-render

**Comment by CJ-Wright** [comment]
@conda-forge/libsodium would it be possible to get this in soon-ish? The lack of toolchain or jinja2 compiler syntax causes this to not be in the gcc7 rebuild graph.

**Comment by minrk** [comment]
@CJ-Wright sorry for losing track of this. Just did a rebase & rerender, so assuming it passes CI, will merge as soon as I notice the green checks.

A "please merge if/when CI passes" button/bot would be really handy.

**Comment by CJ-Wright** [comment]
I was working on an auto ping bot at cf-scripts if you were interested, I just haven't had the time to finish it up.

**Pull request merged**
