### PR TITLE
Fix support for win

### PR DESCRIPTION
**Pull request by nehaljwani**
- Make sure version.h is generated using the vbs script
- Make sure the symbols are exported properly for the generated libs
- Make sure include\sodium is copied correctly

### CODE REVIEW

**Comment by nehaljwani** [comment]
While building pynacl, with this package as a build dependency on Windows, I came across a few issues. This patch fixes them.

**Comment by jakirkham** [comment]
Build number bump? 😉

**Comment by nehaljwani** [comment]
Should I bump the build number only for the windows build by adding a selector, or do it for all?

**Comment by jakirkham** [comment]
We just normally bump the build number for all. Too much hassle to track down issues with packages if the build number varies based on OS as well.

**Comment by nehaljwani** [comment]
Okay, build number has been bumped :)

Although, I would rather have moved the current windows build to 'broken' and then rebuilt it with this.

**Comment by jakirkham** [comment]
They are not exclusive. We can do both. 🙂

**Comment by jakirkham** [comment]
Thanks @nehaljwani.

**Comment by jakirkham** [comment]
FYI the old builds are under the broken label.

screen shot 2017-11-19 at 16 04 36

**Comment by nehaljwani** [comment]
Thank you @jakirkham ! 

I broke ~480 people. I can probably live with that. :disappointed_relieved:

**Pull request merged**
